### PR TITLE
homework_1 summit

### PR DESCRIPTION
**Pull request by hzy24**
[GWPYCamp_Homework_01.pdf](https://github.com/iphysresearch/GWData-Bootcamp/files/13631992/GWPYCamp_Homework_01.pdf)
附件pdf为leecode题代码和结果

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @hzy24
---

**Comment by iphysresearch** [comment]
> ## Good Job!!! @hzy24

@hzy24 
把你的 homework 分支 update branch 一下哈，不然PR这里的check不到你的作业结果哦~

**Comment by hzy24** [comment]
已经update了，辛苦老师了

**Comment by iphysresearch** [comment]
Good Job!!!   @hzy24
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
好的 完成Python编程作业了哈！

**Pull request merged**
