### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by user321102**
Check numpy_submit.txt

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 0
- Score: 0%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 0
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @user321102
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
收到哈！做一做扩展作业吧😊

**Comment by iphysresearch** [comment]
> @iphysresearch Finished~

收到哈！做一做扩展作业吧😊

**Comment by user321102** [comment]
434
解法一：
```python
class Solution(object):
    def countSegments(self, s):
        """
        :type s: str
        :rtype: int
        """
        #直接调用内置函数
        return len(s.split())  
```
解法二：
```python
class Solution(object):
    def countSegments(self, s):
        """
        :type s: str
        :rtype: int
        """
        #定义变量用来储存计数
        count = 0
        
        #对字符串s进行遍历
        for i in range(len(s)):
            #对字符串的每一个元素，如果本身是空格而且前方不是空格，则意味着这是一个segment，同时需要处理i=0的情况
            if s[i] != ' ' and (s[i-1] == ' ' or i == 0):
                #如果满足条件则加1
                count += 1
  
       #返回结果      
        return count
```

**Comment by user321102** [comment]
1869
解法一：
```python
class Solution(object):
    def checkZeroOnes(self, s):
        """
        :type s: str
        :rtype: bool
        """
        #对1的计数
        one_ocunt = 0
        #1连续最长的值
        one_max = 0
        #对0的计数
        zero_count = 0
        #0连续最长的值
        zero_max = 0
        #判断遍历指针在1还是在0
        state = 0

        #对字符串进行遍历
        for i in range(len(s)):
            #如果读取到1，则通过state判断之前是在读0的序列还是1的序列
            #如果是0的序列，则对之前0的序列进行收尾操作，判断0的计数和0最长值的关系，如果0最长值小于计数，则将计数的值赋给0最长值，同时将state设为1，表示接下来是在读取1的序列，同时将1的计数设为1
            #如果是1的序列，则将1的计数加1即可
            if s[i] == '1':
                if state == 0:
                    if zero_max < zero_count:
                        zero_max = zero_count
                    state = 1
                    one_count = 1
                else:
                    one_count += 1
                if i == len(s)-1:
                    if one_max < one_count:
                        one_max = one_count
            #与上方逻辑一致，只是换为读取0的情况   
            else:
                if state == 1:
                    if one_max < one_count:
                        one_max = one_count
                    state = 0
                    zero_count = 1
                else:
                    zero_count += 1
                if i == len(s)-1:
                    if zero_max < zero_count:
                        zero_max = zero_count
        
        #比较1最长值和0最长值，返回要求的值
        if one_max > zero_max:
            return True
        else:
            return False
```
解法二：
```python
class Solution(object):
    def checkZeroOnes(self, s):
        """
        :type s: str
        :rtype: bool
        """
        #调用内置函数split进行分隔，max返回最长的序列，len进行计数，直接返回比较的计算值
        return len(max(s.split('0'))) > len(max(s.split('1')))
```

**Comment by user321102** [comment]
852
解法一：
```python
import numpy as np
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        #借助numpy内置函数直接得到答案
        return np.argmax(arr)
```
解法二：
```python
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        #由于序列严格单增后单减，于是只要判断下降的点在什么地方即可  
        #定义变量用于储存索引
        i = 0
        #如果前一位小于后一位，则索引加一，如果前一位大于后一位，则说明找到了想要的索引
        while True:
            if (arr[i+1] > arr[i]):
                i += 1
            else:
                return i
```
解法三
```python
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        #通过二分法来寻找
        #定义二分法所需要的起点和终点
        start, end = 0, len(arr) - 1
        #当起点和终点间只有一个值时停止循环
        while (start+1 < end):
            #计算中点
            mid = (end + start)//2
            #比较中点前方和后方的点，相应的改变下次需要搜索的区间
            if arr[mid-1] < arr[mid] and arr[mid] < arr[mid+1]:
                start = mid
            elif arr[mid-1] > arr[mid] and arr[mid] > arr[mid+1]:
                end = mid
            #返回最后得到的中点
            else:
                return mid
```

**Comment by user321102** [comment]
1784
解法一：
```python
class Solution(object):
    def checkOnesSegment(self, s):
        """
        :type s: str
        :rtype: bool
        """
        #以0对字符串进行分隔
        s_one = s.split('0')
        #扔掉第一个必定连续的1
        s_one.pop(0)
        #如果剩下的部分为空，则返回True；如果其中最大的元素不为''，则表明还有其他1，返回False
        if s_one == []:
            return True
        elif max(s_one) != '':
            return False
        else:
            return True
```
解法二：
```python
class Solution(object):
    def checkOnesSegment(self, s):
        """
        :type s: str
        :rtype: bool
        """
        #关键就在于寻找0后面的1，直接使用内置关键字in
        return not '01' in s
```

**Comment by user321102** [comment]
162
解法一：
```python
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        #直接使用内置函数返回最大值
        return nums.index(max(nums))
```
解法二：
```python
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        #遍历list找最大的值
        #定义变量来储存最大的值的索引
        index_max = 0
        #对list进行遍历，找到比现在更大的数则替换
        for i in range(1, len(nums)):
            if nums[i] > nums[index_max]:
                index_max = i
        #返回最大值的索引
        return index_max
```
解法三：
```python
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        #考虑使用二分法
        #先定义二分法需要的起点和终点
        start = 0
        end = len(nums) - 1
        #这里的迭代需要格外小心，也是最精妙的地方之所在，与单增单减不同的是，这里数列的增减很任意，希望能够通过二分法确定一个索引，这个索引满足要求的条件
        #大致的思路是，选取一个中点，然后比较中点及其附近的值，依此来判断该如何选取下一个起点和中点。这里假设选取中点及其下一个点来进行比较，如果下一个点大于该点，则说明右侧一定有至少一个极大值，这时候应该将起点移到这里，如果下一个点小于该点，则说明左侧一定有至少一个极大值，应该将终点移到这里
        #随着迭代的次数增多，最后区间会越来越小，不论如何，最后一定会得到起点和终点只相差1，因为相差更多都可以通过取中点来缩小，而只有相差1时取中点的方式便会有影响，(end + start)//2的方式始终是偏向小的值，所以相差为1时的中点就是start，这也保证了之前的比较，即比较中点和下一个点始终是有意义的
        #这也给起点和终点的移动提出了要求，当下一个点大于该点时，起点应该移至mid+1，否则在相差1时便会一直循环，当下一个点小于该点时，终点应该移至mid
        #最后start和end都会收缩到一个值，返回该值即可
        while start < end:
            mid = (end + start) // 2
            if nums[mid+1] > nums[mid]:
                start = mid + 1
            else:
                end = mid
        return start
```

**Pull request merged**
