### PR TITLE
python_numpy_pandas+seaborn可视化+credit_scoring+finetune(全部基础作业)

### PR DESCRIPTION
**Pull request by ShiaLiao**
共6个文件

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @ShiaLiao
---

**Comment by iphysresearch** [comment]
Good Job!!!   @ShiaLiao
---

**Comment by iphysresearch** [comment]
> ## Good Job!!! @ShiaLiao

@ShiaLiao 
你需要update branch一下才能看到你的作业哈！

**Comment by iphysresearch** [comment]
Good Job!!!   @ShiaLiao
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @ShiaLiao
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by ShiaLiao** [comment]
共六个文件，python+numpy+pandas, seaborn, machine learning, finetune

**Pull request merged**
