### PR TITLE
Homework python

### PR DESCRIPTION
**Pull request by gravityrb**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 102
- Score: 94.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 104
- Score: 96.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 102
- Score: 94.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by gravityrb** [comment]
finally succeed!/(ㄒoㄒ)/~~

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @gravityrb
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
@gravityrb 
把 Leetcode 作业也做一下哈？

**Comment by gravityrb** [comment]
> @gravityrb 把 Leetcode 作业也做一下哈？

收到

**Comment by gravityrb** [comment]
- 434 Number of Segments in a String
```python
class Solution:
    def countSegments(self, s: str) -> int:
        #遇见空格，State变为0；遇见其它，State变为1。初始State设为0，计算State从0变为1的次数
        State=0 #初始State设为0
        WordCount=0
        for i in s:
            if i !=' ' and State==0:#当State=0时遇见其它，计数加1
                WordCount+=1
                State=1
            elif i ==' ' and State==1:#当State=1时遇见空格，State=0
                State=0
            else:
                pass
        return(WordCount)
```
屏幕截图 2023-12-11 180507
- 1869 Longer Contiguous Segments of Ones than Zeros
```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        Len1=0#记录由 1 组成的连续子字符串的长度
        Len0=0#记录由 0 组成的连续子字符串的长度
        Count=0
        #建立一个状态变量，若第一个字符为‘0’，State=0
        #若第一个字符为‘1’，State=1
        if s[0]=='0':
            State=0
        else:
            State=1
        #根据状态变量来计数相同连续字符的长度，并与前一个比较长度，保留大的一个数值
        for i in s:
            if i =='0' and State==0:
                Count+=1
            elif i=='1' and State==0:
                if Len0>Count:
                    pass
                else:
                    Len0=Count
                Count=1
                State=1
            elif i=='1' and State==1:
                Count+=1
            elif i=='0' and State==1:
                if Len1>Count:
                    pass
                else:
                    Len1=Count
                Count=1
                State=0
        if s[-1]=='0':
            if Len0>Count:
                pass
            else:
                Len0=Count
        else:
            if Len1>Count:
                pass
            else:
                Len1=Count
        if Len1>Len0:
            return(True)
        else:
            return(False)
```
屏幕截图 2023-12-11 180815
- 1784 Check if Binary String Has at Most One Segment of Ones
```python
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        #建立一个状态变量，第一次遇见‘1’的时候状态变量从0变为1；
        #遇见‘0’之后状态变量从1变为0，
        #记录状态变量从0变为1的次数
        State=0
        Count=0
        for i in s:
            if i=='1' and State==0:
                Count+=1
                if Count>1:
                    break
                State=1
            elif i=='0' and State==1:
                State=0
            else:
                pass
        if Count>1:
            return(False)
        else:
            return(True)
```
屏幕截图 2023-12-11 181116
- 852 Peak Index in a Mountain Array
```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        #从中间选一个点开始，让数值往高处走，若遇数值变小。即最大值
        Length=len(arr)
        StartIndex=int(Length/2)
        #判断两边哪边数值在增大
        #向左增大
        if arr[StartIndex-1]>arr[StartIndex] and arr[StartIndex]>arr[StartIndex+1]:
            for i in range(2,StartIndex+1):
                NewIndex=StartIndex-i
                if arr[NewIndex]<arr[NewIndex+1]:
                    MaxIndex=NewIndex+1
                    break
                else:
                    pass
        #向右增大
        elif arr[StartIndex-1]<arr[StartIndex] and arr[StartIndex]<arr[StartIndex+1]:
            for i in range(2,Length-StartIndex+1):
                NewIndex=StartIndex+i
                if arr[NewIndex]<arr[NewIndex-1]:
                    MaxIndex=NewIndex-1
                    break
                else:
                    pass
        else:
            MaxIndex=StartIndex
        return(MaxIndex)
```
屏幕截图 2023-12-11 181302
- 162 Find Peak Element
```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        Max=nums[0]#将第一个数给max
        Index=0
        #从第二个数开始，一次和前一个进行比较，知道找出最大值
        if len(nums)==1:
            Index=0
        else:
            for i in range(1,len(nums)):
                if nums[i]>Max:
                    Max=nums[i]
                    Index=i
                else:
                    pass
        return(Index)
```
屏幕截图 2023-12-11 181416

**Comment by iphysresearch** [comment]
@gravityrb 
帅呆了哈！👍🏻

**Pull request merged**
