### PR TITLE
resubmit python basic homework

### PR DESCRIPTION
**Pull request by WTLleo**
拓展作业正在做

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---

**Comment by WTLleo** [comment]
434:
class Solution(object):
    def countSegments(self, s):
        count = 0
        for i in range(len(s)):
            if s[i] != ' 'and(s[i - 1] == ' 'or i == 0 )  :
                count = count+1
        return count 
1869：
  def checkZeroOn(self, s: str) -> bool:
        ans=[]
        start=s[0]
        i=1
        count=1
        if sum(map(int,list(s)))==len(s):
            return True
        if sum(map(int,list(s)))==0:
            return False
        while i<len(s):
            if s[i]==start:
                count+=1
            else:
                start=s[i]
                ans.append(count)
                count=1
            i+=1
        ans.append(count)
        if s[0]=="0":
            max0=max(ans[::2])
            max1=max(ans[1::2])
            if max1>max0:
                return True
            else:
                return False
        if s[0]=="1":
            #print(ans)
            max1=max(ans[::2])
            max0=max(ans[1::2])
            if max1>max0:
                return True
            else:
                return False


1784 :

class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        return '01' not in s#s 组成的数字，两种情况：1 全部在最前且连续 或者s 不出现 01字符串

852：

class Solution(object):
  def peakIndexInMountainArray(self, arr):
#严格递增。由于是不会出现在最左最右峰值，不必判断边界。
      l,r = 0,len(arr)-1
      while l <= r:
          mid = (l+r) // 2
          if arr[mid-1] <arr[mid] and arr[mid+1] < arr[mid]:
              return mid
          elif arr[mid-1] > arr[mid]:
              r = mid
          else:
              l = mid

162：
class Solution:#二分查找
    def findPeakElement(self, nums: List[int]) -> int:
        left, right = 0, len(nums) - 1
        while left < right:
            mid = left + (right - left) // 2
            if nums[mid] > nums[mid + 1]:
                right = mid
            else:
                left = mid + 1

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by WTLleo** [comment]
434:
class Solution(object):
def countSegments(self, s):
count = 0
for i in range(len(s)):
if s[i] != ' 'and(s[i - 1] == ' 'or i == 0 ) :
count = count+1
return count
1869：
def checkZeroOn(self, s: str) -> bool:
ans=[]
start=s[0]
i=1
count=1
if sum(map(int,list(s)))==len(s):
return True
if sum(map(int,list(s)))==0:
return False
while i<len(s):
if s[i]==start:
count+=1
else:
start=s[i]
ans.append(count)
count=1
i+=1
ans.append(count)
if s[0]=="0":
max0=max(ans[::2])
max1=max(ans[1::2])
if max1>max0:
return True
else:
return False
if s[0]=="1":
#print(ans)
max1=max(ans[::2])
max0=max(ans[1::2])
if max1>max0:
return True
else:
return False

1784 :

class Solution:
def checkOnesSegment(self, s: str) -> bool:
return '01' not in s#s 组成的数字，两种情况：1 全部在最前且连续 或者s 不出现 01字符串

852：

class Solution(object):
def peakIndexInMountainArray(self, arr):
#严格递增。由于是不会出现在最左最右峰值，不必判断边界。
l,r = 0,len(arr)-1
while l <= r:
mid = (l+r) // 2
if arr[mid-1] <arr[mid] and arr[mid+1] < arr[mid]:
return mid
elif arr[mid-1] > arr[mid]:
r = mid
else:
l = mid

162：
class Solution:#二分查找
def findPeakElement(self, nums: List[int]) -> int:
left, right = 0, len(nums) - 1
while left < right:
mid = left + (right - left) // 2
if nums[mid] > nums[mid + 1]:
right = mid
else:
left = mid + 1

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @WTLleo
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Review by iphysresearch — APPROVED** [review]
@WTLleo 
完成Python基础+扩展作业，Matplotlib+Seaborn数据可视化作业，Sklearn建模和调参作业

**Pull request merged**
