### PR TITLE
Homework-python-numpy-pandas

### PR DESCRIPTION
**Pull request by ymphys**
I rm -rf my local repo, re-forked your repo and re-cloned to my computer
hope this works fine!

### CODE REVIEW

**Comment by ymphys** [comment]
hope this works!

**Comment by iphysresearch** [comment]
Good Job!!!   @ymphys
---
Python homework:
- Total questions: 108
- Correct answers: 104
- Score: 96.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @ymphys
---
Python homework:
- Total questions: 108
- Correct answers: 104
- Score: 96.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @ymphys
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @ymphys
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by ymphys** [comment]
# 434. 
```python
class Solution(object):
    def countSegments(self, s):
        """
        :type s: str
        :rtype: int
        """
        # 初始化计数
        i = 0
        
        # 对 s 中的每个元素进行循环
        for j in range(len(s)):
            # 如果当前字符不是空格且前一个字符是空格或者是第一个字符，则增加计数
            if s[j] != ' ' and (j == 0 or s[j-1] == ' '):
                i += 1
        
        # 返回计数结果
        return i
``` 

# 1869
```python
class Solution(object):
    def checkZeroOnes(self, s):
        """
        :type s: str
        :rtype: bool
        """
        # 将字符串 s 按照字符 '0' 进行分割，得到一个包含子字符串的列表 s1
        s1 = s.split('0')
        # 按照 '1' 分割
        s2 = s.split('1')
        # 计算列表 s1 中各个子字符串的长度，并取其中最大值，赋值给变量 r1
        r1 = max([len(i) for i in s1])
        # 找列表 s2 中各个子字符串的长度的最大值，赋值给变量 r2
        r2 = max([len(i) for i in s2])
        # 返回比较结果，判断是否满足条件：s1 中最长子字符串的长度是否大于 s2 中最长子字符串的长度
        return r1 > r2

``` 

# 1784
```python
class Solution(object):
    def checkOnesSegment(self, s):
        """
        :type s: str
        :rtype: bool
        """
        # 如果 s 包含 “01”，则 s 为“1...01...”，至少有两个连续的“1”段，返回假。
        return '01' not in s
``` 

# 852
```python
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        low = 0  # 设置初始的低位索引
        high = len(arr) - 1  # 设置初始的高位索引

        # 当低位索引小于高位索引时执行循环
        while low < high:
            mid = low + (high - low) // 2  # 计算中间索引，使用 // 运算符确保得到整数结果
            # 检查当前位置和下一个位置的元素大小关系
            if arr[mid] < arr[mid + 1]:
                low = mid + 1  # 如果当前元素小于下一个元素，说明峰值在右侧，更新低位索引
            elif arr[mid] > arr[mid + 1]:
                high = mid  # 如果当前元素大于下一个元素，说明峰值在左侧或当前位置，更新高位索引

        # 返回低位索引，即找到的峰值位置
        return low
``` 

# 162
```python
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        left = 0  # 设置初始的左边界索引
        right = len(nums) - 1  # 设置初始的右边界索引


        # 若数组长度大于2
        while left < right - 1:
            mid = (left + right) // 2  # 计算中间索引，使用 // 运算符确保得到整数结果

            # 如果当前位置的元素大于前后两个位置的元素，说明找到峰值
            if nums[mid] > nums[mid + 1] and nums[mid] > nums[mid - 1]:
                return mid

            # 如果当前位置的元素小于后一个位置的元素，说明峰值在右侧，更新左边界索引，数组长度改变
            if nums[mid] < nums[mid + 1]:
                left = mid + 1
            # 否则说明峰值在左侧，更新右边界索引
            else:
                right = mid - 1  

        # 若数组长度不大于2，返回左右边界索引中较大的那个
        return left if nums[left] >= nums[right] else right
```

**Comment by iphysresearch** [comment]
@ymphys 
你要提交的修改太多了，好多都还是别人作业文件的内容哦。。。。

**Comment by ymphys** [comment]
抱歉老师，我参考满分同学作业的答案找了我错在哪儿，应该是不小心改了别人的内容，我明天重新提交一下Sent from my iPhoneOn Jan 2, 2024, at 22:27, He Wang ***@***.***> wrote:﻿
@ymphys
你要提交的修改太多了，好多都还是别人作业文件的内容哦。。。。

**Comment by iphysresearch** [comment]
Good Job!!!   @ymphys
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Pull request closed without merging**
