### PR TITLE
Homework_python

### PR DESCRIPTION
**Pull request by lepton42**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 8
- Score: 66.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @lepton42
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by lepton42** [comment]
##

**Comment by lepton42** [comment]
## 1. 434. Number of Segments in a String (初级)

### 方法1.
```python
class Solution:
    def countSegments(self, s: str) -> int: 
        #将字符拆分
        ss = s.split()
        #计算数组中的元素个数
        spaces_count =  len(ss)
        
        return spaces_count 
class Solution:
    def countSegments(self, s: str) -> int: 
        #将字符拆分
        ss = s.split()
        #计算数组中的元素个数
        spaces_count =  len(ss)
        
        return spaces_count 
```

### 方法2.
```python
class Solution:
    def countSegments(self, s: str) -> int:         
        segments_count = 0
        i = 0
        #第一个循环
        while i < len(s):
            #向前迭代，若为空格，则跳出，并i += 1
            if s[i] == ' ':  
                i += 1
                continue
            #若不为空格开始，则计算i += 1，且从第一个非空格开始迭代，直到再次出现空格为止
            while i < len(s) and s[i] != ' ': 
                i += 1
            #完成上述循环后，此时记录一个字母，此时字母个数+1
            segments_count += 1
        
        return segments_count
```

**Comment by lepton42** [comment]
## 2.1869. Longer Contiguous Segments of Ones than Zeros(初级)
### 方法1.
```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        begin0,begin1 = 0,0 
        end0,end1 = 0,0
        #循环挑选字符串
        for a in s:
            #判断挑选出的是否为0
            if a == '0':
                #若为0，则开始计算0的个数，并保持1的个数为0
                begin0 += 1
                begin1 = 0
            else:
                #若不为0，则开始计算非0的个数，并保持0的个数为0
                begin0 = 0
                begin1 += 1
            #每次循环后存下对应的值，并比较大小，从而得到最大值
            end0 = max(end0,begin0)
            end1 = max(end1,begin1)
        #判断0和非0的大小，并判断给出1或0
        return end1 > end0 
```

### 方法2.
```python
class Solution:
    def get_num(self , words):
        a = 0
        #传入任意一个连续字符
        for w in words:
            #比较所有字符的长度
            a =  max(len(w) , a)
        #返回最长字符的长度
        return a
        #把for函数直接写到return中
        #return max(len(w) for w in words)
​
    def checkZeroOnes(self, s: str) -> bool:
        #通过切分0得到只包含1的字符数组
        a = self.get_num(s.split('0'))
        #通过切分1得到只包含0的字符数组
        b = self.get_num(s.split('1'))
​
        #通过比较两个并判断，返回1或0
        return a > b
        #不用单独写出参数，直接写到return中
        #return self.get_num(s.split('0')) > self.get_num(s.split('1'))
```
```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        a = max(map(len, s.split('0')))
        b = max(map(len, s.split('1')))
        return a > b
        #return max(map(len, s.split('0'))) > max(map(len, s.split('1')))
```

**Comment by lepton42** [comment]
## 3.1784. Check if Binary String Has at Most One Segment of Ones (初级)

### 方法1.
```python
class Solution:
class Solution:
    def get_num(self , words):
        a = 0
        #传入任意一个连续字符
        for w in words:
            #比较所有字符的长度
            a =  max(len(w) , a)
        #返回最长字符的长度
        return a
​
    def checkOnesSegment(self, s: str) -> bool:
        #挑选出s中分组的1的最大个数
        a = self.get_num(s.split('0'))
        str = ''
        #去掉其中所有的0
        c = str.join(s.split('0'))
        #判断所有1的个数是否全来自一组
        #若c中只有1个值，则为True
        if len(c) == 1:
            a = 2
        #若c中不止又1个值，则为False
        elif (len(c)-a >= 1):
            a = 0
        return a > 1
```

### 方法2.

```python
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        #若存在01，则说明出现了第二个以1开头的，因此返回0
        return '01' not in s
```

**Comment by lepton42** [comment]
## 4.852. Peak Index in a Mountain Array (中级)

### 方法1.
```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        #初始化比较的值，取第一个值
        a = arr[0]
        #针对列表中的值和序号挑选
        for indix, value in enumerate(arr[1::]):
            #若下一次值大于a的值，则更新a的值
            if a < value :
                a = value
            #若下一次值小于a的值，则说明a已经为正序递增的最大值了，此时反向也会满足反序递减
            else:
                #此时满足单增最大值，并返回值
                result = indix
                break
        return result  
```
### 方法2.
```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:      
        #从序号下手，判断向后一个和当前的大小，若存在递减的出现，则此时为需要的序号所在
        for i in range(len(arr)-1):
            if arr[i] > arr[i+1]:
                result = i
                break
        
        return result
```

**Comment by lepton42** [comment]
## 5.162. Find Peak Element (中级)

### 方法1.

```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        #向序列末尾插入最小值，从而保证序列最后的值存在比较的对象
        nums.append(-inf)
        #初始化结果值，并保留中间峰的值
        result = 0
        result_mid = 0
        #从序列中循环挑选
        for i in range(len(nums)-1):
            #若挑选出的值比后一个值大，则确定该位置是一个峰值
            if nums[i] > nums[i+1]:
                result_mid = i
                #并再次判断，若中间结果的峰值较大，则传递为最大峰值，反之则跳过
                if nums[result_mid] >= nums[result]:
                    result = result_mid
        #循环完成所有结果后返回最大峰值
        return result
```
### 方法2.

```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        #二分法查找
        l , r = 0,len(nums)-1
        #确保左边小于右边时可以循环下去
        while l < r:
            #挑选出中值所在序号
            mid = (l+r)//2
            #判断中值右侧是否出现递减
            if nums[mid] > nums[mid+1]:
                #若出现，则此时将右侧变更为中值所在，从而保证峰值一定在重新划定的区间内
                r = mid
            else:
                #若没有出现，则从中值右侧开始记为左侧，从而保证峰值一定在重新划定的区间内
                l = mid+1
        #当最终区间二分化到1为止，此时终止循环，并返回序号
        return r
```

**Comment by iphysresearch** [comment]
@lepton42 
Python 编程作业全部完成了哈！

**Pull request merged**
