### PR TITLE
text2

### PR DESCRIPTION
**Pull request by KL2333**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 107
- Correct answers: 25
- Score: 23.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 107
- Correct answers: 48
- Score: 44.00%
---

**Comment by iphysresearch** [comment]
Bug 已经解决，现在题目总数可以识别为正确的108了哈

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 98
- Score: 90.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 9
- Score: 75.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---

**Comment by KL2333** [comment]
愚钝如我,暂时放弃

**Comment by KL2333** [comment]
@iphysresearch 可以记录了

**Comment by iphysresearch** [comment]
> 愚钝如我,暂时放弃
@KL2333 
你要不再试试？显示不出来成绩往往是因为我这里的homework分支有更新的一次提交，需要你在自己的仓库homework分支上进行update branch，不然的话，你的commit 里会有不唯一的作业文件修改，就会让判作业工作流报错的。

也有同学遇到类型的情况：https://github.com/iphysresearch/GWData-Bootcamp/pull/137#issuecomment-1845666444

**Comment by iphysresearch** [comment]
Good Job!!!   @KL2333
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
@KL2333 

完成Python扩展作业！

**Pull request merged**
