### PR TITLE
Homework Python Part

### PR DESCRIPTION
**Pull request by SDYZZY**
这是 Python、NumPy 和 pandas 部分的基础作业以及拓展作业。

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---

**Comment by SDYZZY** [comment]
中间有一步错误的 force push，已经撤销

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
不错哈！继续pandas 和扩展作业吧哈！

**Comment by iphysresearch** [comment]
Good Job!!!   @SDYZZY
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by SDYZZY** [comment]
### 162. Find Peak Element
```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:

        # 定义一个列表，用于存储所有满足条件的索引
        index_list = []
        # 如果列表只有一个元素，根据题意直接返回之
        if len(nums) == 1:
            return 0
        # 否则，先判断两头的元素是否符合。如果第 0 个元素大于第 1 个元素，则将其添加在 index_list 列表之中
        if nums[0] > nums[1]:            
            index_list.append(0)
        # 如果最后一个元素大于倒数第二个元素，则将其添加在 index_list 列表之中
        if nums[-1] > nums[-2]:
            index_list.append(len(nums)-1)
        # 对于中间的每个元素，判断是否符合条件
        for i in range(1, len(nums)-1):
            # 如果符合则添加到 index_list 列表之中
            if nums[i-1] < nums[i] and nums[i] > nums[i+1]:
                index_list.append(i)
        # 返回列表里面的任意一个元素均可完成题目，这里就返回最后一个        
        return(index_list[-1])
```

### 434. Number of Segments in a String
```python
class Solution:
    def countSegments(self, s: str) -> int:

        # 由题意，“一个片段定义为没有空格的连续序列”，所以根据空格分割字符串
        s = s.split(' ')
        # 连续空格被分割后会产生空字符串''，所以返回的列表里面除了片段以外，还会有若干空字符串，计算其数目
        a = s.count('')
        # 由总的元素个数减去空字符串的个数就可以得到片段的个数
        return len(s) - a
```

### 852. Peak Index in a Mountain Array
```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:

        # 题目已经明确这个列表一定是 mountain 型的，所以直接查找其最大值
        Max = max(arr)
        # 枚举列表，查找最大值对应的索引，返回之
        for index, values in enumerate(arr):
            if values == Max:
                return index
```

### 1784. Check if Binary String Has at Most One Segment of Ones
```python
class Solution:
    def checkOnesSegment(self, s: str) -> bool:

        # 设置计数器为 0
        count = 0
        # 根据 0 对字符串切片，返回一个只有 '1' 和空字符''的列表（如果字符串不含 0，则会直接返回一个只有一个元素（就是这个字符串）的列表
        segments = s.split('0')
        # 对于列表的每一个元素
        for i in segments:
            # 判断 1 是否在其中，如果在则计数器+1
            if '1' in i:
                count += 1
        # 如果计数器的值大于 1，说明不止有一个连续的 1 片段，返回 False
        if count > 1:
                return False
        # 否则，至多一个连续的 1 片段，返回 True
        else:
            return True
```

### 1869. Longer Contiguous Segments of Ones than Zeros
```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:

        # 如果 0 不在字符串里面，肯定符合条件，返回 True
        if '0' not in s:
            return True
        # 如果 1 不在字符串里面，肯定不符合条件，返回 False
        if '1' not in s:
            return False
        # 对于其他情况，将字符串 s 分别根据 '1' 和 '0' 分割
        all_zeros = s.split('1')
        all_ones = s.split('0')
        # 设置 '0' 和 '1' 片段的长度为 1
        len_zeros, len_ones = 1, 1
        # 对于 all_zeros 列表，里面只有 0 构成的片段和空字符串元素''，而每一个空串的长度均为 1，可以不用单独考虑
        for i in all_zeros:
            # 对于每一个 0 片段元素，如果其长度大于之前找到的最大长度，则将最大长度设置为这一值
            if len(i) > len_zeros:
                len_zeros = len(i)
        # 同理，对于每一个 1 片段元素，如果其长度大于之前找到的最大长度，则将最大长度设置为这一值
        for i in all_ones:
            if len(i) > len_ones:
                len_ones = len(i)
        # 如果 0 片段的长度小于 1 片段，则符合条件，返回 True
        if len_zeros < len_ones:
            return True
        # 否则返回 False
        else:
            return False
```

**Comment by SDYZZY** [comment]
@iphysresearch 老师您好，这是我的基础作业和拓展作业，请帮忙记录一下成绩吧，谢谢！

**Comment by iphysresearch** [comment]
> @iphysresearch 老师您好，这是我的基础作业和拓展作业，请帮忙记录一下成绩吧，谢谢！

@SDYZZY 
棒👍🏻，恭喜完成Python编程的基础作业和扩展作业！

**Pull request merged**
