### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by LogicMoriaty**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @LogicMoriaty
---

**Comment by LogicMoriaty** [comment]
## 434

```python
class Solution:
    def countSegments(self, s: str) -> int:
        # 分割字符串为单词列表
        wordslist = s.split()
        # 返回单词列表的长度
        return len(wordslist)
```

## 1869

```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        max_ones, max_zeros, count_ones, count_zeros = 0, 0, 0, 0

        for char in s:
            if char == '1':
                # 如果字符是'1'，增加1的计数器，重置0的计数器
                count_ones += 1
                count_zeros = 0
            else:
                # 如果字符是'0'，增加0的计数器，重置1的计数器
                count_zeros += 1
                count_ones = 0

            # 更新最大长度
            max_ones = max(max_ones, count_ones)
            max_zeros = max(max_zeros, count_zeros)

        # 如果1的最长连续子字符串长于0的，则返回True
        return max_ones > max_zeros
```

## 1784

```python
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        #只要字符串中不包含01就返回TRUE，否则，返回FALSE
        return "01" not in s
```

## 852

```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        # 使用二分查找法来找到山顶，初始先令left和right分别为数组的两端
        left, right = 0, len(arr) - 1

        #当left小于right时，继续循环，反之退出循环，返回left
        while left < right:
            #找到中点元素
            mid = (left + right) // 2
            if arr[mid] < arr[mid + 1]:
                # 如果中点元素小于其右侧元素，则山顶在右侧
                left = mid + 1
            else:
                # 否则山顶在左侧或就是中点
                right = mid
```

## 162

```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        #首先判断数组的长度是否为1，若为1，则可直接返回1作为峰值位置
        if len(nums) == 1:
            return 0
        #再对长度不为1的情况进行分类讨论
        if len(nums) != 1:
            #考虑峰值为两端元素的情况
            if nums[len(nums)- 1] > nums[len(nums)- 2]:#末端元素为峰值
                return len(nums)- 1
            if nums[0] > nums[1]:#起始端元素为峰值
                return 0
            #考虑中间元素为峰值，从第二个元素开始判断
            left = 1
            while left < len(nums):
                if nums[left] > nums[left + 1] and nums[left] > nums[left - 1]:#当严格大于两边相邻元素时，返回峰值位置
                    return left
                else:
                    left  += 1#否则继续判断下一个元素
        return left #返回位置

```

**Comment by LogicMoriaty** [comment]
上面的852少粘贴了两行代码，下面为完整的852代码

## 852

```python
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        # 使用二分查找法来找到山顶，初始先令left和right分别为数组的两端
        left, right = 0, len(arr) - 1

        #当left小于right时，继续循环，反之退出循环，返回left
        while left < right:
            #找到中点元素
            mid = (left + right) // 2
            if arr[mid] < arr[mid + 1]:
                # 如果中点元素小于其右侧元素，则山顶在右侧
                left = mid + 1
            else:
                # 否则山顶在左侧或就是中点
                right = mid

        return left #返回位置
```

**Comment by iphysresearch** [comment]
Good Job!!!   @LogicMoriaty
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @LogicMoriaty
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by LogicMoriaty** [comment]
@iphysresearch 老师好，麻烦老师记一下成绩(=^▽^=)

**Review by iphysresearch — APPROVED** [review]
@LogicMoriaty 
恭喜完成Python编程的基础作业和扩展作业哈！

**Pull request merged**
