### PR TITLE
Homework2

### PR DESCRIPTION
**Pull request by JunFan0**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 86
- Score: 79.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 8
- Score: 80.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 86
- Score: 79.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 8
- Score: 80.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 86
- Score: 79.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by JunFan0** [comment]
@iphysresearch

**Comment by iphysresearch** [comment]
> @iphysresearch

要不把扩展作业也做一下吧哈？

**Comment by iphysresearch** [comment]
Good Job!!!   @JunFan0
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by JunFan0** [comment]
434
https://leetcode.cn/problems/number-of-segments-in-a-string/submissions/488799544
1869
https://leetcode.cn/problems/longer-contiguous-segments-of-ones-than-zeros/submissions/488800236
1784
https://leetcode.cn/problems/check-if-binary-string-has-at-most-one-segment-of-ones/submissions/488800834
852
https://leetcode.cn/problems/peak-index-in-a-mountain-array/submissions/488801069
162
https://leetcode.cn/problems/find-peak-element/submissions/4888014
代码在我的作业ExtensionTasks.txt里面。
@iphysresearch

**Comment by iphysresearch** [comment]
@JunFan0 
棒哈！恭喜完成全部作业！

**Pull request merged**
