### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by cttt1024**
python/numpy/pandas basic HW

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 10
- Score: 83.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by cttt1024** [comment]
434. Number of Segments in a String
class Solution(object):
    def countSegments(self, s):
        #利用split()函数把输入字符串按空格划分，之后用len()函数返回长度
        return len(s.split())

1869. Longer Contiguous Segments of Ones than Zeros
class Solution(object):
    def checkZeroOnes(self, s):
        #定义列表num储存1和0的最长长度
        num=[0,0]
        #定义temp变量储存当前要数的对象(1或0)，首先从字符串开头选取
        temp=s[0]
        #创建变量tempnum统计临时长度
        tempnum=0
        #创建for循环统计字符串中最长1和0的个数
        for i in s:
            #下一个字符没变，数量加1
            if i==temp:
                tempnum+=1
            #下一个字符变了，判断临时长度是否大于之前统计的最大长度，是的话更新最大长度。之后开始新的统计
            else:
                if tempnum > num[int(temp)]:
                    num[int(temp)]=tempnum
                tempnum=1
                temp=i
        #对于最后一次统计的临时长度做一次判断
        else:
            if tempnum > num[int(temp)]:
                    num[int(temp)]=tempnum
        #返回1的长度是否大于0的长度
        return num[1]>num[0]

1784. Check if Binary String Has at Most One Segment of Ones
class Solution(object):
    def checkOnesSegment(self, s):
        #利用split()函数把字符串按“0”分开，因为字符串由“1”开始，所以我们只取第二个元素及之后的部分作判断
        temp=s.split('0')[1:]
        #如果有不止一段“1”，那么temp中存在非空值，此时返回False，否则返回True
        for i in temp:
            if i != '':
                return False       
        return True

852. Peak Index in a Mountain Array
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        #直接利用内置函数max获得最大值，index获得位置
        return arr.index(max(arr))

162. Find Peak Element
class Solution(object):
    def findPeakElement(self, nums):
        #直接利用内置函数max获得最大值，index获得位置，按index返回元素
        return nums.index(max(nums))

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @cttt1024
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
@cttt1024 
恭喜完成了 Python 数据可视化的基础作业和拓展作业，以及 Python 数据可视化的基础作业和扩展作业！

**Pull request merged**
