### PR TITLE
Homework 2023/12/03

### PR DESCRIPTION
**Pull request by qmaimai**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 1
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 1
- Score: 10.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 1
- Score: 8.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 1
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 1
- Score: 8.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 1
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 1
- Score: 8.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 1
- Score: 0%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 9
- Score: 90.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @qmaimai
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by qmaimai** [comment]
- [434. Number of Segments in a String](https://leetcode.com/problems/number-of-segments-in-a-string/) 
```python
class Solution:
    def countSegments(self, s: str) -> int:
        # 初始化循环参数
        count=0
        ju=True
        # 遍历全部s中全部字符
        for i in s:
            # 判断i是否非" "
            if i!=" ":
                # 判断前一次迭代是否为" "
                if ju:
	                # 计数加1
                    count+=1
                    ju=False
                # 继续下一次迭代
                continue
            # 判断i是否为" "并记录
            else:
                ju=True
        # 返回单词数
        return count
```
- [1869. Longer Contiguous Segments of Ones than Zeros](https://leetcode.com/problems/longer-contiguous-segments-of-ones-than-zeros/description/) 
```python
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        # 初始化循环参数
        ju=True
        count1=0
        count0=0
        # 初始化list记录segment长度，最小值初始化为0
        count1maxs=[0, ]
        count0maxs=[0, ]
        # 遍历s所有字符
        for i in s:
            # 判断s是否为"1"
            if i=="1":
                # 判断上次迭代是否为"0"
                if not ju:
                    ju=True
                    # 记录上一个"0"segment长度
                    count0maxs.append(count0)
                    # "0"segment长度计数归0
                    count0=0
                # "1"segment长度计数加1
                count1+=1
            # 判断s是否为"0"
            else:
                # 判断上次迭代是否为"1"
                if ju:
                    ju=False
                    # 记录上一个"1"segment长度
                    count1maxs.append(count1)
                    # "1"segment长度计数归0
                    count1=0
                # "0"segment长度计数加1
                count0+=1
        # 记录最后一个segment长度
        if ju:
            count1maxs.append(count1)
        else:
            count0maxs.append(count0)
        # 比较最长"1"segment和最长"0"segment,并返回结果
        return max(count1maxs) > max(count0maxs)
```
 
- [1784. Check if Binary String Has at Most One Segment of Ones](https://leetcode.com/problems/check-if-binary-string-has-at-most-one-segment-of-ones/description/) (初级)
```python
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        # 初始化循环参数
        ju=True
        # 自s第二个字符起遍历字符
        for i in s[1:]:
            # 判断是否出现"0",并记录
            if i=="0":
                ju=False
            # 若出现"0"后又出现"1"则返回False
            elif i=="1" and not ju:
                return False
        # 循环完成则返回True
        return True
```

- [852. Peak Index in a Mountain Array](https://leetcode.com/problems/peak-index-in-a-mountain-array/description/) (中级)
```python
class Solution:
    def peakIndexInMountainArray(self, arr: list[int]) -> int:
        # 取list长度
        length=len(arr)
        # 初始化循环参数
        ju = True
        i=length
        # 二分法寻找peak
        for n in range(1,length):
            # 根据前一次迭代指标，计算本次指标
            i = i + (- 2 * ju + 1) * int(length / 2**n+0.5)
            # 判断是否为peak
            ju = arr[i] > arr[i+1]
            if arr[i-1] < arr[i] and ju:
                # 返回peak指标
                return i
```
- [162. Find Peak Element](https://leetcode.com/problems/find-peak-element/description/)

```python
class Solution:
    def findPeakElement(self, nums: list[int]) -> int:
        # 取list长度
        length=len(nums)
        # 若list长度为1，或首元素为peak，则返回0
        if length==1 or nums[0] > nums[1]: return 0
        # 若list尾元素为peak，则返回末尾指标
        if nums[-2] < nums[-1]: return length-1
        # 从list两端起寻找peak
        for i in range(int(length / 2 + 0.5)):
            # 从1号元素起判断peak
            if nums[i] < nums[i+1] > nums[i+2]: return i+1
            # 从倒数第二个元素起判断peak
            if nums[length-3-i] < nums[length-2-i] > nums[length-1-i]: return length-2-i
```

**Comment by iphysresearch** [comment]
@qmaimai 
恭喜完成Python编程作业哈！

**Pull request merged**
