### PR TITLE
Homework Py-basic

### PR DESCRIPTION
**Pull request by GeyuQin**
Python基础作业

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @GeyuQin
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GeyuQin
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GeyuQin
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GeyuQin
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
@GeyuQin 
别忘了Python扩展作业哦~ 做完然后我给记成绩！

**Comment by iphysresearch** [comment]
Good Job!!!   @GeyuQin
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by GeyuQin** [comment]
Python拓展作业
1.
```
    def countSegments(self, s: str) -> int:
        if len(s)==0:
            return 0        
        if s[0] == ' ':
            j = 0
        else:
            j = 1 
        #将字符串分为空格起始与单词起始两类
        for i in range(len(s)-1):
            #对整个字符串遍历
            if (s[i] == ' ') & (s[i+1] != ' ') :
                j = j + 1
            #空格后接连续不是空格的字符，判定为单词
        return j
```
2.
```def checkZeroOnes(self, s: str) -> bool:
        if len(max(s.split('0'))) > len(max(s.split('1'))):
            return True
        else:
            return False
        #按0,1分割并分别计算最大元素的长度，将其比较
```
3. 
```    def checkOnesSegment(self, s: str) -> bool:
        for i in range(len(s)-1):
            if (s[i] == '0') & (s[i+1] == '1'):
                return False
        return True
        #只要出现0，并且在0后出现1则不满足条件
```
4.
```
def peakIndexInMountainArray(self, arr: List[int]) -> int:
        #要求时间复杂度在log(n)，使用二分法
        left,right=0,len(arr)-1
        while left<=right :
            mid=(left+right)//2
            if arr[mid-1]<=arr[mid] and arr[mid+1]<=arr[mid]:
                return mid
            elif arr[mid-1]>arr[mid]:
                right=mid
            else:
                left=mid  
```
5.
```
def findPeakElement(self, nums: List[int]) -> int:
        # 二分法
        left, right = 0, len(nums) - 1
        while left <= right:
            mid = (left + right) // 2
            #剃掉全局单调的数列
            if mid>0 and nums[mid]<nums[mid-1]:
                #峰值在前
                right=mid-1
            elif mid<len(nums)-1 and nums[mid]<nums[mid+1]:
                #峰值在后
                left=mid+1
            else:
                return mid
```

**Review by iphysresearch — APPROVED** [review]
@ljq2088 
完成Python基础+扩展作业，Matplotlib数据可视化作业！

**Pull request merged**
