### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by GitLuckyRan**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @GitLuckyRan
---
Python homework:
- Total questions: 108
- Correct answers: 106
- Score: 98.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GitLuckyRan
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GitLuckyRan
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @GitLuckyRan
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by GitLuckyRan** [comment]
434：字符串中的单词数
     res = s.split(' ')            #按空格分开
        for i in range(res.count('')):
            res.remove('')
        return len(res)
        # return len(res) if all(res) else len(res)-res.count('')   #如果res中没有‘’ 则返回res的长度，否者减去‘’的个数
        
1869：哪种连续子字符串更长

class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        return len(max(s.split('0')))>len(max(s.split('1')))

1784：检查二进制字符串字段

class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        length=len(s)
        i=length-1
        while i>0:
            if(s[i]=='1' and s[i-1]=='0'):     #利用倒序如果出现‘1’‘0’,又因为第一个字符为1，这样就会造成连续个1的字段数量大于1
                break
            i=i-1
        
        return i==0

852：山脉数组的峰顶索引
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        #return arr.index(max(arr))
        left = 0
        right = len(arr)-1                 #利用二分法找最大值
        while left<right:
            mid = (left+right)//2
            if arr[mid]>arr[mid-1] and arr[mid] >arr[mid+1]:
                return mid
            elif arr[mid]<arr[mid-1]:
                right = mid###3
            elif arr[mid]<arr[mid+1]:
                left = mid###
        return left

162：寻找峰值
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        return nums.index(max(nums))        #最大值肯定是峰值     



        # left = 0                             #二分法寻找个领域的最小值  
        # right = len(nums)-1           
        # while left<right:    
        #     mid = (left+right)//2            
        #     if nums[mid]<nums[mid+1]:
        #         left = mid+1
        #     else:
        #         right = mid
        # return left
 

        # if(len(nums)==1):                    #面对只有list只有一个值的列表   
        #     return 0
        # if(nums[0]>nums[1]):                 #面对第一个比第二大的情况
        #     return 0
        # if(nums[len(nums)-1]>nums[len(nums)-2]):    #面对最后一个比倒数第二个大的情况
        #     return len(nums)-1
        # length=len(nums)
        # i=1
        # while i<length-1:                                #对于中间的比两边大的情况
        #     if(nums[i]>nums[i-1] and nums[i]>nums[i+1]):
        #         return i
        #         i=i+2
        #     else:
        #         i=i+1 
@iphysresearch  commit

**Comment by iphysresearch** [comment]
@GitLuckyRan 
恭喜完成第二部分的所有作业！

**Pull request merged**
