### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by Haihao-Shi**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @Haihao-Shi
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
@Haihao-Shi 
把Python编程的扩展作业也做一下吧哈！

**Comment by HaihaoSHI** [comment]
[LEETCODE_hw.pdf](https://github.com/iphysresearch/GWData-Bootcamp/files/13821212/LEETCODE_hw.pdf)

**Comment by iphysresearch** [comment]
@Haihao-Shi 
恭喜完成Python基础+扩展作业，Seaborn数据可视化作业，模型建模和调优作业！

**Pull request merged**
