### PR TITLE
Submit homework

### PR DESCRIPTION
**Pull request by zhuan-ning**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @fatefades
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @fatefades
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @fatefades
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @fatefades
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by zhuan-ning** [comment]
> you'd like us to change this.

Yes, I'd like you to change this.

**Pull request closed without merging**
