### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by yelishuang**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @yelishuang
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 0
- Score: 0%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @yelishuang
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by yelishuang** [comment]
class Solution(object):
    def countSegments(self, s):
        """
        :type s: str
        :rtype: int
        """
        count=0
        if s=='':
            return 0
        lst=s.split(' ')//按空格分割字符串
        for word in lst:
            if word=='':
                count+=1 //统计空字符数量，然后剔除
        return len(lst)-count

**Comment by yelishuang** [comment]
class Solution(object):
    def checkZeroOnes(self, s):
        """
        :type s: str
        :rtype: bool
        """
        max_1 = 0//1最大长度
        max_0 = 0//0最大长度
        count_1 = 0//统计1的长度
        count_0 = 0//统计0的长度
        last = 2//当前位上一位字符
        for i in s:
            if i != last:
                count_1 = 0
                count_0 = 0
                last = i //不同重新统计
            if i == '1':
                count_1 +=1 //统计1长度
                if count_1 > max_1:
                    max_1 = count_1//大于最大长度，置换
            elif i == '0':
                count_0 +=1//统计0长度
                if count_0 > max_0:
                    max_0 = count_0 //大于最大长度，置换         
        return max_1 > max_0 //返回最大长度比较情况

**Comment by yelishuang** [comment]
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        left=0
        right=len(arr)-1
        mid=(left+right)//2
        while mid!=left and mid!=right:
            lm=(left+mid)//2  //left与mid中间
            rm=(right+mid)//2  //left与mid中间
            if arr[mid]>=arr[rm] and arr[mid]>=arr[lm]:
                    left=lm
                    right=rm //两边低中间高，缩进，让left缩进到lm，right缩进到rm
            elif   arr[mid] >= arr[rm] and arr[rm] >= arr[right]:
                    right=mid
                    mid=lm   //mid 比 rm高，rm比right高，右边确定下降趋势，舍去，让mid等于lm ，right等于mid
            elif arr[mid] >= arr[lm] and arr[lm] >= arr[left]:
                    left = mid
                    mid = rm //mid 比lm高，lm 比 left 高，左边边确定下降趋势，舍去，让mid等于rm ，leftt等于mid
        if  arr[right]>arr[left]:
            return right
        else:
            return left

**Comment by yelishuang** [comment]
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        """
        return nums.index(max(nums))最大值是一个peak，找最大值的索引就行

**Comment by iphysresearch** [comment]
@yelishuang 

不好意思，作业都没有完整完成，没有成绩。。。

**Pull request closed without merging**
