### PR TITLE
Homework of WangZun

### PR DESCRIPTION
**Pull request by Doubleking-1**
Basic homework of python

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @Doubleking-1
---

**Comment by iphysresearch** [comment]
Good Job!!!   @Doubleking-1
---
Python homework:
- Total questions: 108
- Correct answers: 103
- Score: 95.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @Doubleking-1
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Review by iphysresearch — APPROVED** [review]
@Doubleking-1 
扩展作业的五个题也做一下呗哈？

**Comment by Doubleking-1** [comment]
class Solution:
    def countSegments(self, s: str) -> int:
        word_count = 0  # 初始化单词计数为0
        in_word = False  # 设置一个flag，判断当前字符是否是一个空白字符，如果不是空白字符，则这个字符在单词中

        # 遍历字符串中的每个字符
        for char in s:
            # 如果是空白字符，设置标志为False，表示不在单词中
            if char.isspace():  
                in_word = False  
            # 如果当前字符不是空白字符，则说明这个字符在单词中，计数并把in_word设置为True，直到这个单词结束
            elif not in_word:  
                word_count += 1
                in_word = True  

        return word_count  # 返回单词总数

**Comment by Doubleking-1** [comment]
```
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        zero_max, one_max = 0, 0                # 连续为1或0个数的最大值
        zero_count, one_count = 0, 0          # 数1或0的个数

        pointer = 0                                     # 定义一个指针，从第一个字符开始
        # 当指针游到最后一个字符时结束循环
        while pointer !=len(s):
            # 如果当前指针指的是0，就开始循环，记录连续是0的个数，直到指针指到1. 把记录到是0的个数和之前zero_max比较，取最大值，继续大循环
            if s[pointer] == '0':
                while pointer != len(s) and s[pointer] == '0':
                    zero_count += 1
                    pointer +=1
                zero_max = max(zero_max,zero_count)
                zero_count = 0
                continue
            # 和以上一样的逻辑
            elif s[pointer] == '1':
                while pointer != len(s) and s[pointer] == '1':
                    one_count += 1
                    pointer += 1
                one_max = max(one_max,one_count)
                one_count = 0
                continue
        # 最后zero_max 和one_max 记录的是字符串中 连续是0或1 的最大个数。判断大小后输出结果
        if one_max > zero_max:
            return True
        else:
            return False

```

**Comment by Doubleking-1** [comment]
```
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        flag =True
        pointer = 0
        # 定义一个指针，遍历每一个字符
        while pointer !=len(s):
            # 找到第一个出现0的索引位置（指针），如果没有0， 就是True
            if s[pointer] != '0':
                pointer += 1
                continue
            # 找到之后，检查0后面有没有1，如果有就是False，如果没有就是True
            else:
                ss = s[pointer:]
                if '1' in ss:
                    flag = False
                    break
                else:
                    flag = True
                    break
        return flag
```

**Comment by Doubleking-1** [comment]
```
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        # 二分法，先选择左右两下标。
        left = 0
        right = len(arr)-1
        mid = 0
        while left < right:
            # 根据左右坐标选定中间坐标
            mid = left + int((right-left)/2)
            # 如果mid的值大于左右两侧，就是所要找的值
            if arr[mid] > arr[mid-1] and arr[mid] > arr[mid+1]:
                break
            # 如果mid的右边更大，说明峰值在右边，此时让left指到mid，扔掉左边，缩小范围
            elif arr[mid+1] > arr[mid]:
                left = mid
           # 如果mid的左边更大，说明峰值在左边，此时让right指到mid，扔掉右边，缩小范围
            elif arr[mid+1] < arr[mid]:
                right = mid

        return mid
```

**Comment by Doubleking-1** [comment]
leetcode 162
```python
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        # 如果数组就一个，直接输出0
        if len(nums)==1:
            return 0
        for i in range(0,len(nums)):
            # 如果检查第一个，就只和右边的比骄
            if i == 0:
                if nums[i] > nums[i+1]:
                    return i
            # 如果检查最后一个，就只和左边比较
            elif i == len(nums)-1:
                if nums[i] > nums[i-1]:
                    return i
            # 否则就和两边比骄
            elif nums[i] > nums[i-1] and nums[i] > nums[i+1]:
                return i
```

**Comment by Doubleking-1** [comment]
@iphysresearch

**Review by iphysresearch — APPROVED** [review]
@Doubleking-1 
恭喜完成Python编程的全部作业哈！

**Pull request merged**
