### PR TITLE
submit homework of python,numpy and pandas

### PR DESCRIPTION
**Pull request by kaigekphy**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @kaigekphy
---
Python homework:
- Total questions: 108
- Correct answers: 102
- Score: 94.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @kaigekphy
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @kaigekphy
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by kaigekphy** [comment]
434
class Solution:
    def countSegments(self, s):
#初始化结果
        segment_count = 0
#遍历s中每一个字符
        for i in range(len(s)):
#对于第一个字符，如果不是空格，结果加一；对于后面的字符，如果当前字符不是空格，而且前一个字符是空格，结果加一；
#i=0时，s[-1]不会报错
            if (i == 0 or s[i - 1] == ' ') and s[i] != ' ':
                segment_count += 1

        return segment_count

**Comment by kaigekphy** [comment]
1869
`class Solution:`
`    def checkZeroOnes(self, s: str) -> bool:`
#初始化
`        num1b,num1n,num0b,num0n=0,0,0,0`
#遍历字符串
`        for k in range(len(s)):`
#如果当前字符为1
`            if s[k]=='1':`
#令当前连续字符串0长度为0
`                num0n=0`
#令当前连续字符串1长度加一
`                num1n+=1`
#如果当前连续字符串1长度大于已经记录的最大连续字符串1长度
`                if num1n>num1b:`
#更新最大连续字符串1长度为当前连续字符串1长度
`                    num1b=num1n`
#如果当前字符为不为1，按题目要求就是0
`            else :`
#令当前连续字符串1长度为0
`                num1n=0`
#令当前连续字符串0长度加一
`                num0n+=1`
#如果当前连续字符串0长度大于已经记录的最大连续字符串0长度
`                if num0n>num0b:`
#更新最大连续字符串0长度为当前连续字符串0长度
`                    num0b=num0n`
#比较最大连续字符串1长度和最大连续字符串0长度，并返回比较结果
`        return num1b>num0b`

**Comment by kaigekphy** [comment]
1869
`class Solution:`
`    def checkZeroOnes(self, s: str) -> bool:`
#将字符串按'0'或'1'分开，得到连续的1或者连续的0字符串列表
`        s1,s0=s.split('0'),s.split('1')`
得到连续的1或者连续的0字符串列表中最长的字符串，比较它们的长度并输出结果
`        return max([len(i) for i in s1])>max([len(j) for j in s0])`

**Comment by kaigekphy** [comment]
1784
`class Solution:`
`    def checkOnesSegment(self, s: str) -> bool:`
#初始化结果
`        num=0`
#遍历字符串中的字符
`        for k in range(len(s)):`
#如果是第一个字符且该字符为1，或者前一个字符不是1且该字符为1
`            if ( k==0 or s[k-1]!='1' ) and s[k]=='1':`
#结果加一
`                num+=1`
#如果结果是0或1，即小于等于1，则输出True，否则输出False
`        return num<=1`

**Comment by kaigekphy** [comment]
> a=1

**Review by iphysresearch — APPROVED** [review]
@kaigekphy 
恭喜完成Python编程作业哈！

**Pull request merged**
