### PR TITLE
Basic HW of Python/Numpy/Pandas

### PR DESCRIPTION
**Pull request by DrizzleatDusk**
Add basic homework files of Python/Numpy/Pandas.

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @DrizzleatDusk
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @DrizzleatDusk
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Review by iphysresearch — COMMENTED** [review]
@DrizzleatDusk 
再加把油，Python基础作业都做对，扩展作业5个题也做一下哈！

**Comment by iphysresearch** [comment]
Good Job!!!   @DrizzleatDusk
---
Python homework:
- Total questions: 108
- Correct answers: 107
- Score: 99.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @DrizzleatDusk
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by DrizzleatDusk** [comment]
Leetcode Homeworks:

``` Python
# 434
class Solution(object):
    def countSegments(self, s):
        """
        :type s: str
        :rtype: int
        """
        # 使用字符串split方法产生列表
        # 然后返回列表中元素的个数。
        return len(s.split())
    

# 1869
class Solution(object):
    def checkZeroOnes(self, s):
        """
        :type s: str
        :rtype: bool
        """
        list0 = s.split('1')    # 以1为间隔分解字符串
        list1 = s.split('0')    # 以0为间隔分解字符串
        max_len0 = max(len(list0[i]) for i in range(len(list0)))    # 连续1的最大长度
        max_len1 = max(len(list1[i]) for i in range(len(list1)))    # 连续0的最大长度
        return max_len1 > max_len0
    

# 1784
class Solution(object):
    def checkOnesSegment(self, s):
        """
        :type s: str
        :rtype: bool
        """
        list1 = s.replace('0', ' ').split()     # 以0序列为间隔分解字符串
        return len(list1) < 2   # 列表长度小于2说明1的连续段数小于2
        


# 852
class Solution(object):
    def peakIndexInMountainArray(self, arr):
        """
        :type arr: List[int]
        :rtype: int
        """
        i_left, i_right = 0, len(arr)-1     # 指向当前被选段的头尾
        while True:     # 二分法
            i = (i_right - i_left) // 2 + i_left    # 中间位置指标
            if arr[i-1] < arr[i] > arr[i+1]:    # 满足条件返回
                return i
            if arr[i] > arr[i-1]:   # 最大元素在前半段
                i_left = i
            else:   # 最大元素在后半段
                i_right = i


# 162
class Solution(object):
    def findPeakElement(self, nums):
        """
        :type nums: List[int]
        :rtype: int
        实现思路与#852没区别
        """
        i_left, i_right = 0, len(nums)-1     # 指向当前被选段的头尾
        while True:     # 二分法
            if (i_right-i_left) < 2:    # 数组长度小于3时直接比较
                return i_left if nums[i_left] > nums[i_right] else i_right
            # 长度大于等于3则直接使用 #852 中的算法
            i = (i_right - i_left) // 2 + i_left   
            if nums[i-1] < nums[i] > nums[i+1]:    
                return i
            if nums[i] > nums[i-1]:
                i_left = i
            else:
                i_right = i
```

@iphysresearch I'd like to submit this as the final version of the Python homework.

**Review by iphysresearch — APPROVED** [review]
@DrizzleatDusk 
恭喜完成Python的基础或扩展作业，还有matplotlib数据可视化作业哈！

**Pull request merged**
