### PR TITLE
python basic Homework

### PR DESCRIPTION
**Pull request by kotaro9808**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @kotaro9808
---
Python homework:
- Total questions: 108
- Correct answers: 104
- Score: 96.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 0
- Score: 0%
---
Pandas homework:
- Total questions: 12
- Correct answers: 0
- Score: 0%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @kotaro9808
---
Python homework:
- Total questions: 108
- Correct answers: 104
- Score: 96.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
@kotaro9808 
加把油，把Python基础作业和扩展作业都做好，我再给你记录成绩！

**Comment by kotaro9808** [comment]
好的，谢谢老师
| |
物理院22级赵少东
| |
|
***@***.***
|
---- Replied Message ----
| From | He ***@***.***> |
| Date | 1/4/2024 02:20 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [iphysresearch/GWData-Bootcamp] python basic Homework (PR #278) |

@kotaro9808
加把油，把Python基础作业和扩展作业都做好，我再给你记录成绩！

**Comment by iphysresearch** [comment]
@kotaro9808 
加速了哈~~  时间所剩不多了~~

**Review by iphysresearch — APPROVED** [review]
@kotaro9808 
我算你完成了Python基础作业了~

**Comment by kotaro9808** [comment]
谢谢老师


| |
物理院22级赵少东
| |
|
***@***.***
|
---- Replied Message ----
| From | He ***@***.***> |
| Date | 1/4/2024 17:39 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [iphysresearch/GWData-Bootcamp] python basic Homework (PR #278) |

@iphysresearch approved this pull request.

@kotaro9808
我算你完成了Python基础作业了~

**Pull request merged**
