### PR TITLE
Python homework 1 try 231217

### PR DESCRIPTION
**Pull request by Tangfengjie**

### CODE REVIEW

**Comment by iphysresearch** [comment]
Good Job!!!   @Tangfengjie
---

**Comment by iphysresearch** [comment]
Good Job!!!   @Tangfengjie
---

**Comment by iphysresearch** [comment]
Good Job!!!   @Tangfengjie
---
Python homework:
- Total questions: 108
- Correct answers: 105
- Score: 97.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 11
- Score: 91.00%
---

**Comment by iphysresearch** [comment]
Good Job!!!   @Tangfengjie
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Review by iphysresearch — APPROVED** [review]
@Tangfengjie 
很不错哈！把扩展作业的五个题也做一下吧哈？

**Comment by iphysresearch** [comment]
Good Job!!!   @Tangfengjie
---
Python homework:
- Total questions: 108
- Correct answers: 108
- Score: 100.00%
---
Numpy homework:
- Total questions: 10
- Correct answers: 10
- Score: 100.00%
---
Pandas homework:
- Total questions: 12
- Correct answers: 12
- Score: 100.00%
---

**Comment by Tangfengjie** [comment]
# Leetcode 作业
# 434. Number of Segments in a String (初级)
class Solution:
    def countSegments(self, s: str) -> int:
        # 初始化计数器和标记变量
        count = 0
        is_word = False

        # 遍历字符串中的每个字符
        for char in s:
            # 如果当前字符不是空格且之前的字符是空格或者是字符串的开头
            if char != ' ' and not is_word:
                count += 1
                is_word = True
            # 如果当前字符是空格
            elif char == ' ':
                is_word = False
        
        return count
    
# 1869. Longer Contiguous Segments of Ones than Zeros (初级)
class Solution:
    def checkZeroOnes(self, s: str) -> bool:
        # 最简单的思路就是一个个数呗
        # 如果是1，或者0，那就计数
        # 然后如果说新的字符串长度大于之前的记录就更新
        # 读取完一遍就直接返回
        # 用字典保存1或者0的最长数目
        max_dict = {"0": 0, "1": 0}
        temp_dict = {"0": 0, "1": 0}
        # 使用tcha作为临时变量
        # 如果说下一次读入与tcha一样就长度加1
        # 如果说下一次读入与tcha不一样就记录长度
        # 并且将tch赋值为新读入的变量
        tcha = s[0]
        for cha in s: 
            if tcha == cha:
                temp_dict[tcha] += 1
            else:
                if  max_dict[tcha] < temp_dict[tcha]:
                    max_dict[tcha] = temp_dict[tcha]
                temp_dict[tcha] = 0
                tcha = cha
                temp_dict[tcha] += 1
        # 运行完之后对最后一个判断的变量进行比较
        if  max_dict[tcha] < temp_dict[tcha]:
            max_dict[tcha] = temp_dict[tcha]
        # 输出bool型的变量
        if max_dict["0"] < max_dict["1"]:
            return True
        else:
            return False

# 1784. Check if Binary String Has at Most One Segment of Ones (初级)
class Solution:
    def checkOnesSegment(self, s: str) -> bool:
        # 题目中不含有前导0
        # 然后必须要包含零个或者一个由‘1’组成字段
        # 因为这里‘1’后面只有可能是‘0’
        # 所以就是去数到底有几个‘10’
        # 因为不含有前导0，并且字符串不为空
        # 所以必然会有一个‘1’，那么久不存在0个‘1’字段
        # 唯一要考虑的是末尾的‘1’后面没有‘0’
        # 所以在末尾加上‘0’之后去数到底有几个‘10’
        return (s + "0").count("10") == 1

# 852. Peak Index in a Mountain Array (中级)
class Solution:
    def peakIndexInMountainArray(self, arr: List[int]) -> int:
        # 本来是要用二分法的
        # 但想想这不就是找一个最大值么
        # 估计python内置的的最大值算法是分治之类的算法
        # 复杂度应该是log（n）样子，直接找就好
        return arr.index(max(arr))
        \
# 162. Find Peak Element (中级)
class Solution:
    def findPeakElement(self, nums: List[int]) -> int:
        # 这道题目里面找到的是任意峰值即可
        # 那显然如果老老实实去找个max总是慢了
        # 就找一个局部解，二分法
        # 定义左右的边界l，r
        l, r = 0, len(nums) - 1
        # 当左边l小于右边r的时候继续搜索
        while l < r:
            # 要去找一个小山峰
            # 选择中间的mid
            # 就去比较mid和左边哪个大
            mid = (l + r) >> 1
            # 这里因为mid是往小取
            # 所以说mid必须+1
            # 否则会出现l=mid死循环
            if nums[mid] > nums[mid+1]:
                r = mid
            else:
                l = mid +1
        return l

@iphysresearch 提交python leetcode作业

**Review by iphysresearch — APPROVED** [review]
@Tangfengjie 
恭喜完成Python编程的基础作业和扩展作业哈！

**Pull request merged**
